
name: PowerShell Lint (PSScriptAnalyzer)

on:
  push:
    paths:
      - '**/*.ps1'
      - '**/*.psm1'
      - '**/*.psd1'
  pull_request:
    paths:
      - '**/*.ps1'
      - '**/*.psm1'
      - '**/*.psd1'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PowerShell
        uses: PowerShell/PowerShell@v1
        with:
          pwsh-version: '7.4.x'

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer -Scope CurrentUser -Force

      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Continue'
          $paths = @('src', 'scripts')
          $settings = 'PSScriptAnalyzerSettings.psd1'
          $results = Invoke-ScriptAnalyzer -Path $paths -Recurse -Settings $settings -Verbose:$false -ErrorAction Continue
          if ($results) {
            $results | Format-Table -AutoSize
            $hasIssues = $results | Where-Object { $_.Severity -in @('Error','Warning') }
            if ($hasIssues) { Write-Error "PSScriptAnalyzer found issues." }
          }
